package prolog;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.util.concurrent.Callable;

import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

@Command(name = "prolog", mixinStandardHelpOptions = true, version = "prolog 1.0", description = "This challenge is to build your own prolog interpreter")
public class Prolog implements Callable<Result> {

    public static int VERBOSE_LEVEL = 0;

    public static boolean verbose() {
        return VERBOSE_LEVEL >= 1;
    }
    public static boolean verbose2() {
        return VERBOSE_LEVEL >= 2;
    }
    public static boolean verbose3() {
        return VERBOSE_LEVEL >= 3;
    }

    public static void main(String[] args) {
        var prolog = new Prolog();
        var cmd = new CommandLine(prolog);
        var exitCode = cmd.execute(args);
        cmd.getExecutionResult();
        System.exit(exitCode);
    }

    @Option(names = "-v", description = "-v specifies verbose level 1")
    final boolean verbose = false;
    @Option(names = "-vv", description = "-vv specifies verbose level 2")
    final boolean verbose2 = false;
    @Option(names = "-vvv", description = "-vvv specifies verbose level 3")
    final boolean verbose3 = false;

    @Override
    public Result call() {
        if (this.verbose) {
            VERBOSE_LEVEL = 1;
        }
        if (this.verbose2) {
            VERBOSE_LEVEL = 2;
        }
        if (this.verbose3) {
            VERBOSE_LEVEL = 3;
        }
        System.out.println("done");
        return new Result();
    }
}