package prolog;

public enum Token {
    POINT,
    UNIFY,
    COMMA,
    LPARENT,
    RPARENT,
    ATOM,
    NUMBER,
    VARIABLE,
    EOF,
    QUOTED_ATOM,
    COMMENT,
    ARITHMETIC_OPERATOR,
    RBRACKET,
    LBRACKET,
    COMPARISON_OPERATOR,
    ARITHMETIC_INEQUALITY_OPERATOR,
    ARRAY_OF_CHARACTERS, QUERY, UNIFY_WITH_OCCUR_CHECK;

}
