package prolog;/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;

import java.io.*;
import java.net.URISyntaxException;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ParserTest  extends Tester {
    @AfterEach
    protected void CloseReader() throws IOException {
        super.CloseReader();
    }


    @Test void test() throws URISyntaxException, IOException {
        // Arrange
        ReadReader("valid-programs.txt");

        while (reader.ready()) {
            var line = reader.readLine();
            if (!line.equals("")) {
                System.out.println(line);
                var lexer = new Lexer(line);
                var parser = new Parser(lexer);

                // Action
                var program = parser.parseProgram();
                System.out.println(program);

                // Assert
                assertNotNull(program);
            }
        }
    }


}
