/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import prolog.Lexer;


import java.io.*;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Paths;
import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class LexerTest  extends Tester {
    @AfterEach
    void CloseReader() throws IOException {
        super.CloseReader();
    }


    @Test void test() throws URISyntaxException, IOException {
        // Arrange
        ReadReader("valid-tokens.txt");

        while (reader.ready()) {
            var line = reader.readLine();
            if (!line.equals("")) {
                var lexer = new Lexer(line);

                // Action
                var tokens = lexer.tokens();
                System.out.println(tokens.toString());

                // Assert

                assertNotNull(tokens);
                assertTrue(tokens.size() > 0);
            }
        }
    }
}
