/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import prolog.Lexer;
import prolog.Parser;

import java.io.*;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Paths;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ParserTest {

    private BufferedReader reader;

    void ReadReader(String testfile) throws FileNotFoundException, URISyntaxException {
        URL resource = ParserTest.class.getResource("tests/"+testfile);
        File file = Paths.get(resource.toURI()).toFile();
        reader = new BufferedReader(new FileReader(file));
    }

    @AfterEach
    void CloseReader() throws IOException {
        if (reader != null) {
            reader.close();
        }
    }

    @Test void test() throws URISyntaxException, IOException {
        // Arrange
        ReadReader("valid-programs.txt");

        while (reader.ready()) {
            var line = reader.readLine();
            if (!line.equals("")) {
                System.out.println(line);
                var lexer = new Lexer(line);
                var parser = new Parser(lexer);

                // Action
                var program = parser.parseProgram();
                System.out.println(program);

                // Assert
                assertNotNull(program);
            }
        }
    }


}
